export const GET_ALL_STUDENTS = "GET_ALL_STUDENTS";
export const REQUEST_STUDENTS = "REQUEST_STUDENTS";
export const RECEIVE_STUDENTS = "RECEIVE_STUDENTS";
export const SELECT_STUDENT = "SELECT_STUDENT";
